05_day/crud1/crud1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crud1/', include('crud1app.urls')),
]

05_day/crud1/crud1app/urls.py
from django.urls import path
from . import views

app_name = 'crud1'
urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create, name='create'),
    # path('form/', views.form, name='form'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    # path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
]

05_day/crud1/crud1app/models.py
from django.db import models

# Create your models here.
class Crud(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()

05_day/crud1/crud1app/forms.py
from django import forms
from .models import Crud
class CrudForm(forms.ModelForm):
    # title = forms.CharField(max_length=20)
    # content = forms.CharField()
    class Meta:
        model = Crud
        fields = '__all__'

05_day/crud1/crud1app/views.py
from django.shortcuts import render, redirect
from .models import Crud
from .forms import CrudForm

def home(request):
    crud = Crud.objects.all()
    context = {
        'crud' : crud
    }
    return render(request, 'crud1app/home.html', context)

# def form(request):
#     return render(request, 'crud1app/create.html')

def create(request):
    if request.method == 'POST':
        form = CrudForm(request.POST)
        if form.is_valid():
            crud = form.save()
            return redirect('crud1:detail', crud.pk)
        # title = request.POST.get('title')
        # content = request.POST.get('content')
        # crud = Crud.objects.create(
        #     title = title,
        #     content = content
        # )
        # crud.save()
        return redirect('crud1:home')
    else:
        form = CrudForm()
        context = {
            'form' : form
        }
        return render(request, 'crud1app/create.html', context)
    
def detail(request, pk):
    crud = Crud.objects.get(pk=pk)
    context = {
        'crud' : crud
    }
    return render(request, 'crud1app/detail.html', context)

def delete(request, pk):
    crud = Crud.objects.get(pk=pk)
    crud.delete()
    return redirect('crud1:home')

# def edit(request, pk):
#     crud = Crud.objects.get(pk=pk)
#     context = {
#         'crud' : crud
#     }
#     return render(request, 'crud1app/edit.html', context)

def update(request, pk):
    crud = Crud.objects.get(pk=pk)
    if request.method == 'POST':
        form = CrudForm(request.POST, instance=crud)
        if form.is_valid():
            form.save()
            return redirect('crud1:detail', crud.pk)
    else:
        form = CrudForm(instance=crud)
    context = {
        'form' : form,
        'crud' : crud
    }
    return render(request, 'crud1app/update.html', context)

05_day/crud1/crud1app/templates/crud1app/create.html
{% extends 'base.html' %}
{% block content %}

<h1>CREATE</h1>

<form action="{% url 'crud1:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value='SUBMIT'>
</form>

{% endblock content %}

05_day/crud1/crud1app/templates/crud1app/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>DETAIL</h1><br>
<hr>
<p>TITLE : {{ crud.title }}</p>
<p>CONTENT : {{ crud.content }}</p>
<hr>
<form action="{% url 'crud1:delete' crud.pk%}" method='POST'>
    {% csrf_token %}
    <input type="submit" value="DELETE">
</form>
<a href="{% url 'crud1:home' %}">HOME</a>
<a href="{% url 'crud1:update' crud.pk%}">EDIT</a>
 
{% endblock content %}

05_day/crud1/crud1app/templates/crud1app/home.html
{% extends 'base.html' %}

{% block content %}

<h1>HOME</h1><br>
<a href="{% url 'crud1:create' %}">CREATE</a>
<hr>
{% for cruds in crud %}
    <a href="{% url 'crud1:detail' cruds.pk %}">
        <p>TITLE : {{ cruds.title }}</p>
    </a>
    <p>CONTENT : {{ cruds.content }}</p>
    <hr>
{% endfor %}

{% endblock content %}

05_day/crud1/crud1app/templates/crud1app/update.html
{% extends 'base.html' %}

{% block content %}

<h1>EDIT</h1><br>
<hr>
<form action="{% url 'crud1:update' crud.pk%}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value='SUBMIT'>
</form>
<hr>
<a style='height: ;' href="{% url 'crud1:detail' crud.pk %}">DETAIL</a>
   
{% endblock content %}

05_day/crud1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <title>CRUD PJT</title>
</head>
<body>

  {% block content %}
  {% endblock content %}
  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>