03_day/review1/articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name='index'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
]

03_day/review1/review1/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
]

03_day/review1/articles/models.py
from django.db import models

# articles/models.py
class Article(models.Model): #article app에서 사용할 게시글 Article
    title = models.CharField(max_length=20) # models에서 title은 문자열 형태, 글자수 지정
    content = models.TextField() # 글자수 지정없이 사용 가능

 

03_day/review1/articles/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'articles/index.html')

def throw(request):
    return render(request, 'articles/throw.html'
    )

def catch(request):
    # message를 받을건데 request 안쪽에 GET방식에 들어있는 데이터중에서 get해
    message = request.GET.get('message') 
    # print(message)
    context={
        'message' : message
    }
    return render(request, 'articles/catch.html', context)

03_day/review1/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}

<h1>여기는 catch입니다.</h1>
<h2>throw에서 보낸 데이터는 '{{ message }}'입니다.</h2>
<a href="http://127.0.0.1:8000/articles/throw">throw로 이동</a>
{% endblock content %}

03_day/review1/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}

<h1>여기는 base.html을 상속받은 index입니다.</h1>

{% endblock content %}

03_day/review1/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}

<h1>여기는 throw입니다.</h1>

<form action="{% url 'articles:catch' %}" methood="GET">
    <label for="message">보내고 싶은 메세지</label>
    <input type="text" name="message" id="message">
    <input type="submit" name="" id="">
</form>
{% endblock content %}